name: Release Changelog
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Switch to default branch
        run: |
          DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
          echo "Default branch is $DEFAULT_BRANCH"
          git checkout $DEFAULT_BRANCH
      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: ./cliff.toml
          args: --strip header
      - name: Commit and push updated CHANGELOG.md
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG.md for ${{ github.ref_name }}" || echo "No changes to commit"
          git push
